export type QentrahOwnerType = "broker" | "developer" | "RED";

export type QentrahOidcClaims = {
  iss?: string;
  aud?: string | string[];
  sub?: string;
  azp?: string;
  client_id?: string;
  exp?: number;
  iat?: number;
  jti?: string;
  scope?: string | string[];
  scp?: string[];
  email?: string | null;
  name?: string | null;
  picture?: string | null;
  org_id?: string | null;
  orgId?: string | null;
  organizationId?: string | null;
  org_slug?: string | null;
  orgSlug?: string | null;
  organizationSlug?: string | null;
  org_role?: string | null;
  orgRole?: string | null;
  organizationRole?: string | null;
  org_permissions?: string[];
  orgPermissions?: string[];
  organizationPermissions?: string[];
  entitlements?: string[] | string;
  permissions?: string[];
  role?: string | null;
  broker_id?: string | null;
  brokerId?: string | null;
  red_id?: string | null;
  redId?: string | null;
  developer_id?: string | null;
  developerId?: string | null;
  owner_type?: QentrahOwnerType | string | null;
  owner_id?: string | null;
  [claim: string]: unknown;
};
