export {
  ModulePanel,
  ModulePanelContent,
  ModulePanelHeader,
  ModulePanelTabHeader,
  ModulePanelBody,
  ModulePanelFooter,
  ModulePanelTitle,
  ModulePanelDescription,
  ModulePanelCloseButton,
  ModulePanelFullscreenToggle,
  ModulePanelResizeHandle,
  type ModulePanelProps,
  type ModulePanelContentProps,
  type ModulePanelHeaderProps,
  type ModulePanelTabHeaderProps,
  type ModulePanelBodyProps,
  type ModulePanelFooterProps,
  type ModuleTab,
} from "./module-panel"
