/** Back-compat barrel — prefer `@/domains/organization/api` or module imports. */
export type {
  OrganizationMember,
  OrganizationInvitation,
  OrganizationInvitationAcceptance,
  OrganizationInviteLink,
  McpPermissionResource,
  McpPermissionAction,
  OrganizationApiKeyResource,
  OrganizationApiKeyAction,
  OrganizationApiKeyPermission,
  OrganizationApiKeyExpiry,
  McpConnectionPermission,
  OrganizationMcpConnection,
  OrganizationApiKey,
  OrganizationRole,
  OrganizationCapabilities,
} from "./types";

export {
  listOrganizationMembers,
  updateOrganizationMemberRole,
  removeOrganizationMember,
  createOrganizationInvitation,
  listOrganizationInvitations,
  cancelOrganizationInvitation,
  acceptOrganizationInvitation,
  createOrganizationInviteLink,
  cancelOrganizationInviteLink,
  acceptOrganizationInviteLink,
  listOrganizationRoles,
  createOrganizationRole,
  updateOrganizationRole,
  deleteOrganizationRole,
  listOrganizationMcpConnections,
  createOrganizationMcpConnection,
  updateOrganizationMcpConnection,
  revokeOrganizationMcpConnection,
  rotateOrganizationMcpConnection,
  listOrganizationApiKeys,
  createOrganizationApiKey,
  rotateOrganizationApiKey,
  revokeOrganizationApiKey,
  getOrganizationCapabilities,
  updateAuthOrganization,
} from "./index";
