"use client"

import { useState, type FormEvent } from "react"
import { useMutation } from "convex/react"
import type { Id } from "../../../../convex/_generated/dataModel"
import { api } from "../../../../convex/_generated/api"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { WorkspaceLink } from "@/components/layout/workspace-link"
import { logger } from "@/lib/logger"

type Option = { id: string; name: string }
type Engagement = { _id: Id<"engagements">; name: string; clientId: Id<"clients">; currency: string }

export function FinanceCommandPanel({ organizationId, view, configured, clients, projects, engagements, invoices }: { organizationId: string; view: string; configured: boolean; clients: Option[]; projects: Option[]; engagements: Engagement[]; invoices: Array<{ id: string; title: string; status: string }> }) {
  const [busy, setBusy] = useState(false)
  const configure = useMutation(api.finance.commands.configureFinance), createTax = useMutation(api.finance.commands.createTaxRule), createVendor = useMutation(api.finance.commands.createVendor), createExpense = useMutation(api.finance.commands.createExpense), createInvoice = useMutation(api.finance.commands.createInvoice), recordPayment = useMutation(api.finance.commands.recordInvoicePayment), createEstimate = useMutation(api.finance.commands.createEstimate), receiveRetainer = useMutation(api.finance.commands.receiveRetainer), createBudget = useMutation(api.finance.commands.createBudget), createBank = useMutation(api.finance.commands.createBankAccount), openPeriod = useMutation(api.finance.commands.openAccountingPeriod)
  async function submit(event: FormEvent<HTMLFormElement>, command: (data: FormData) => Promise<unknown>) { event.preventDefault(); setBusy(true); try { await command(new FormData(event.currentTarget)); event.currentTarget.reset() } catch (error) { logger.error("finance.command_failed", { view, error }) } finally { setBusy(false) } }
  if (!configured) return <Panel title="Configure finance"><form onSubmit={(event) => void submit(event, (data) => configure({ organizationId, baseCurrency: string(data, "currency"), fiscalYearStartMonth: number(data, "month"), periodStartAt: date(data, "start"), periodEndAt: dateEnd(data, "end") }))} className="grid gap-2 sm:grid-cols-5"><Input name="currency" defaultValue="USD" maxLength={3} required /><Input name="month" type="number" min="1" max="12" defaultValue="1" required /><DateFields /><Submit busy={busy} /></form></Panel>
  if (view === "rate-cards") return <Panel title="Rate cards"><p className="text-xs text-muted-foreground">Rates are owned by Resource Planning and referenced by allocations, time, and profitability.</p><WorkspaceLink href="/resources?view=rate-cards" className="mt-3 inline-block text-sm font-semibold text-primary hover:underline">Open rate cards</WorkspaceLink></Panel>
  if (view === "tax") return <Panel title="Add tax rule"><form onSubmit={(event) => void submit(event, (data) => createTax({ organizationId, name: string(data, "name"), jurisdiction: string(data, "jurisdiction"), rateBasisPoints: number(data, "rate"), calculation: string(data, "calculation") as "exclusive" | "inclusive", exempt: false, effectiveFrom: date(data, "effective") }))} className="grid gap-2 sm:grid-cols-5"><Input name="name" placeholder="Tax name" required /><Input name="jurisdiction" placeholder="Jurisdiction" required /><Input name="rate" type="number" min="0" placeholder="Basis points" required /><select name="calculation" className={selectClass}><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option></select><Input name="effective" type="date" required /><Submit busy={busy} /></form></Panel>
  if (view === "vendors") return <Panel title="Add vendor"><form onSubmit={(event) => void submit(event, (data) => createVendor({ organizationId, name: string(data, "name"), currency: string(data, "currency"), taxIdentifier: optional(data, "tax") }))} className="grid gap-2 sm:grid-cols-4"><Input name="name" placeholder="Vendor name" required /><Input name="currency" defaultValue="USD" maxLength={3} required /><Input name="tax" placeholder="Tax identifier" /><Submit busy={busy} /></form></Panel>
  if (view === "expenses" || view === "payable") return <Panel title="Record expense"><form onSubmit={(event) => void submit(event, (data) => createExpense({ organizationId, description: string(data, "description"), incurredAt: date(data, "date"), projectId: optional(data, "project") as Id<"projects"> | undefined, currency: string(data, "currency"), amountMinor: money(data, "amount"), exchangeRateMicros: rate(data) }))} className="grid gap-2 sm:grid-cols-3 xl:grid-cols-7"><Input name="description" placeholder="Expense description" required /><select name="project" className={selectClass}><option value="">No project</option>{projects.map(option)}</select><Input name="date" type="date" required /><Input name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required /><Input name="currency" defaultValue="USD" maxLength={3} required /><Rate /><Submit busy={busy} /></form></Panel>
  if (view === "invoices" || view === "receivable") return <Panel title="Create invoice"><form onSubmit={(event) => void submit(event, (data) => createInvoice({ organizationId, clientId: string(data, "client") as Id<"clients">, projectId: optional(data, "project") as Id<"projects"> | undefined, issueAt: date(data, "issue"), dueAt: dateEnd(data, "due"), currency: string(data, "currency"), exchangeRateMicros: rate(data), lines: [{ description: string(data, "description"), quantity: 1, unitAmountMinor: money(data, "amount") }] }))} className="grid gap-2 sm:grid-cols-3 xl:grid-cols-9"><select name="client" required className={selectClass}><option value="">Client</option>{clients.map(option)}</select><select name="project" className={selectClass}><option value="">No project</option>{projects.map(option)}</select><Input name="description" placeholder="Line description" required /><Input name="issue" type="date" required /><Input name="due" type="date" required /><Input name="amount" type="number" min="0" step="0.01" placeholder="Amount" required /><Input name="currency" defaultValue="USD" maxLength={3} required /><Rate /><Submit busy={busy} /></form></Panel>
  if (view === "payments") return <Panel title="Record invoice payment"><form onSubmit={(event) => void submit(event, (data) => recordPayment({ organizationId, invoiceId: string(data, "invoice") as Id<"financeInvoices">, amountMinor: money(data, "amount"), exchangeRateMicros: rate(data), receivedAt: date(data, "date"), method: string(data, "method") }))} className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><select name="invoice" required className={selectClass}><option value="">Posted invoice</option>{invoices.filter((item) => ["posted", "partially_paid"].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Input name="amount" type="number" min="0.01" step="0.01" required /><Input name="date" type="date" required /><Input name="method" placeholder="Payment method" required /><Rate /><Submit busy={busy} /></form></Panel>
  if (view === "estimates") return <Panel title="Create estimate"><form onSubmit={(event) => void submit(event, (data) => createEstimate({ organizationId, title: string(data, "title"), clientId: string(data, "client") as Id<"clients">, currency: string(data, "currency"), exchangeRateMicros: rate(data), lines: [{ description: string(data, "description"), quantity: 1, unitAmountMinor: money(data, "amount") }] }))} className="grid gap-2 sm:grid-cols-3 xl:grid-cols-7"><Input name="title" placeholder="Estimate title" required /><select name="client" required className={selectClass}><option value="">Client</option>{clients.map(option)}</select><Input name="description" placeholder="Line description" required /><Input name="amount" type="number" min="0" step="0.01" required /><Input name="currency" defaultValue="USD" maxLength={3} required /><Rate /><Submit busy={busy} /></form></Panel>
  if (view === "retainers") return <Panel title="Receive retainer"><form onSubmit={(event) => void submit(event, (data) => receiveRetainer({ organizationId, engagementId: string(data, "engagement") as Id<"engagements">, amountMinor: money(data, "amount"), exchangeRateMicros: rate(data), receivedAt: date(data, "date"), method: string(data, "method") }))} className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6"><select name="engagement" required className={selectClass}><option value="">Engagement</option>{engagements.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><Input name="amount" type="number" min="0.01" step="0.01" required /><Input name="date" type="date" required /><Input name="method" placeholder="Payment method" required /><Rate /><Submit busy={busy} /></form></Panel>
  if (view === "project-budgets" || view === "engagement-budgets") { const project = view === "project-budgets"; return <Panel title={project ? "Add project budget" : "Add engagement budget"}><form onSubmit={(event) => void submit(event, (data) => createBudget({ organizationId, name: string(data, "name"), scopeType: project ? "project" : "engagement", scopeId: string(data, "scope"), periodStartAt: date(data, "start"), periodEndAt: dateEnd(data, "end"), category: string(data, "category"), currency: string(data, "currency"), amountMinor: money(data, "amount"), exchangeRateMicros: rate(data) }))} className="grid gap-2 sm:grid-cols-3 xl:grid-cols-9"><Input name="name" placeholder="Budget name" required /><select name="scope" required className={selectClass}><option value="">Scope</option>{(project ? projects : engagements.map((item) => ({ id: item._id, name: item.name }))).map(option)}</select><Input name="category" placeholder="Category" required /><DateFields /><Input name="amount" type="number" min="0" step="0.01" required /><Input name="currency" defaultValue="USD" maxLength={3} required /><Rate /><Submit busy={busy} /></form></Panel> }
  if (view === "banking") return <Panel title="Add bank account"><form onSubmit={(event) => void submit(event, (data) => createBank({ organizationId, name: string(data, "name"), currency: string(data, "currency") }))} className="grid gap-2 sm:grid-cols-3"><Input name="name" placeholder="Bank account name" required /><Input name="currency" defaultValue="USD" maxLength={3} required /><Submit busy={busy} /></form></Panel>
  if (view === "period-close") return <Panel title="Open accounting period"><form onSubmit={(event) => void submit(event, (data) => openPeriod({ organizationId, name: string(data, "name"), startAt: date(data, "start"), endAt: dateEnd(data, "end") }))} className="grid gap-2 sm:grid-cols-4"><Input name="name" placeholder="Period name" required /><DateFields /><Submit busy={busy} /></form></Panel>
  return null
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-border bg-card p-4"><h2 className="mb-3 text-sm font-semibold">{title}</h2>{children}</section> }
function Submit({ busy }: { busy: boolean }) { return <Button type="submit" size="sm" disabled={busy}>{busy ? "Saving…" : "Save"}</Button> }
function DateFields() { return <><Input name="start" type="date" aria-label="Start date" required /><Input name="end" type="date" aria-label="End date" required /></> }
function Rate() { return <Input name="rate" type="number" min="1" defaultValue="1000000" aria-label="Base exchange rate in millionths" required /> }
function option(item: Option) { return <option key={item.id} value={item.id}>{item.name}</option> }
function string(data: FormData, key: string) { return String(data.get(key) ?? "").trim() }
function optional(data: FormData, key: string) { return string(data, key) || undefined }
function number(data: FormData, key: string) { return Math.round(Number(data.get(key) ?? 0)) }
function money(data: FormData, key: string) { return Math.round(Number(data.get(key) ?? 0) * 100) }
function rate(data: FormData) { return number(data, "rate") }
function date(data: FormData, key: string) { return Date.parse(`${string(data, key)}T00:00:00.000Z`) }
function dateEnd(data: FormData, key: string) { return Date.parse(`${string(data, key)}T23:59:59.999Z`) }
const selectClass = "h-9 min-w-0 rounded-md border border-border bg-background px-3 text-xs text-foreground"
