import { v } from "convex/values";
import type { Id } from "../_generated/dataModel";
import { mutation, type MutationCtx } from "../_generated/server";
import { financeAccess } from "./access";
import { calculateTax, convertToBase } from "./calculation";
import { financeError, postJournal, requireFinanceSettings, systemAccount, type LedgerLineInput } from "./ledger";
import { scopeTypeValidator, taxCalculationValidator } from "./validators";
import { expenseSearchProjection, invoiceSearchProjection, paymentSearchProjection } from "./search";
import { emitAutomationEvent } from "../automations/events";

const lineInput = v.object({ description: v.string(), quantity: v.number(), unitAmountMinor: v.number(), taxRuleId: v.optional(v.id("financeTaxRules")), projectId: v.optional(v.id("projects")), engagementId: v.optional(v.id("engagements")), serviceKey: v.optional(v.string()) });

const defaultAccounts = [
  ["1000", "Cash", "asset", "cash"], ["1100", "Accounts receivable", "asset", "accounts_receivable"], ["2000", "Accounts payable", "liability", "accounts_payable"],
  ["2100", "Tax payable", "liability", "tax_payable"], ["1150", "Recoverable tax", "asset", "tax_receivable"], ["2200", "Retainer liability", "liability", "retainer_liability"], ["4000", "Service revenue", "revenue", "revenue"],
  ["5000", "Operating expense", "expense", "expense"], ["6900", "Foreign exchange gain or loss", "revenue", "fx_gain_loss"],
] as const;

export const configureFinance = mutation({
  args: { organizationId: v.string(), baseCurrency: v.string(), fiscalYearStartMonth: v.number(), periodStartAt: v.number(), periodEndAt: v.number() }, returns: v.id("financeSettings"),
  handler: async (ctx, args) => {
    const actor = await financeAccess(ctx, args.organizationId, "create"); const baseCurrency = currency(args.baseCurrency); interval(args.periodStartAt, args.periodEndAt);
    if (!Number.isInteger(args.fiscalYearStartMonth) || args.fiscalYearStartMonth < 1 || args.fiscalYearStartMonth > 12) throw financeError("INVALID_FISCAL_MONTH", "Fiscal year start month must be 1 through 12.");
    const existing = await ctx.db.query("financeSettings").withIndex("by_org", (q) => q.eq("organizationId", args.organizationId)).unique(); const now = Date.now();
    if (existing && existing.baseCurrency !== baseCurrency) { const journal = await ctx.db.query("financeJournalEntries").withIndex("by_org_date", (q) => q.eq("organizationId", args.organizationId)).first(); if (journal) throw financeError("BASE_CURRENCY_LOCKED", "Base currency cannot change after the first posted journal."); }
    const settingsId = existing?._id ?? await ctx.db.insert("financeSettings", { organizationId: args.organizationId, baseCurrency, fiscalYearStartMonth: args.fiscalYearStartMonth, invoicePrefix: "INV", nextInvoiceNumber: 1, createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    if (existing) await ctx.db.patch(existing._id, { baseCurrency, fiscalYearStartMonth: args.fiscalYearStartMonth, updatedAt: now });
    for (const [code, name, type, systemKey] of defaultAccounts) {
      const account = await ctx.db.query("financeAccounts").withIndex("by_org_code", (q) => q.eq("organizationId", args.organizationId).eq("code", code)).unique();
      if (!account) await ctx.db.insert("financeAccounts", { organizationId: args.organizationId, code, name, type, systemKey, active: true, createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    }
    const period = (await ctx.db.query("financeAccountingPeriods").withIndex("by_org_end", (q) => q.eq("organizationId", args.organizationId).eq("endAt", args.periodEndAt)).collect()).find((item) => item.startAt === args.periodStartAt && !item.deletedAt);
    if (!period) await ctx.db.insert("financeAccountingPeriods", { organizationId: args.organizationId, name: new Date(args.periodStartAt).toISOString().slice(0, 7), startAt: args.periodStartAt, endAt: args.periodEndAt, status: "open", createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    return settingsId;
  },
});

export const createTaxRule = mutation({
  args: { organizationId: v.string(), name: v.string(), jurisdiction: v.string(), rateBasisPoints: v.number(), calculation: taxCalculationValidator, exempt: v.boolean(), effectiveFrom: v.number(), effectiveTo: v.optional(v.number()) }, returns: v.id("financeTaxRules"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); nonnegative(args.rateBasisPoints, "Tax rate"); if (args.rateBasisPoints > 100_000) throw financeError("INVALID_TAX_RATE", "Tax rate exceeds the supported limit."); if (args.effectiveTo) interval(args.effectiveFrom, args.effectiveTo); const liability = await systemAccount(ctx, args.organizationId, "tax_payable"); const now = Date.now(); return ctx.db.insert("financeTaxRules", { ...args, name: text(args.name, "Tax name"), jurisdiction: text(args.jurisdiction, "Tax jurisdiction"), liabilityAccountId: liability._id, active: true, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); },
});

export const openAccountingPeriod = mutation({
  args: { organizationId: v.string(), name: v.string(), startAt: v.number(), endAt: v.number() }, returns: v.id("financeAccountingPeriods"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); await requireFinanceSettings(ctx, args.organizationId); interval(args.startAt, args.endAt); const candidates = await ctx.db.query("financeAccountingPeriods").withIndex("by_org_end", (q) => q.eq("organizationId", args.organizationId).gte("endAt", args.startAt)).take(120); if (candidates.some((period) => !period.deletedAt && period.startAt <= args.endAt)) throw financeError("ACCOUNTING_PERIOD_OVERLAP", "Accounting periods cannot overlap."); const now = Date.now(); return ctx.db.insert("financeAccountingPeriods", { organizationId: args.organizationId, name: text(args.name, "Period name"), startAt: args.startAt, endAt: args.endAt, status: "open", createdByUserId: actor.userId, createdAt: now, updatedAt: now }); },
});

export const createBudget = mutation({
  args: { organizationId: v.string(), name: v.string(), scopeType: scopeTypeValidator, scopeId: v.string(), periodStartAt: v.number(), periodEndAt: v.number(), category: v.string(), currency: v.string(), amountMinor: v.number(), exchangeRateMicros: v.number() }, returns: v.id("financeBudgets"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); interval(args.periodStartAt, args.periodEndAt); nonnegative(args.amountMinor, "Budget"); const now = Date.now(); return ctx.db.insert("financeBudgets", { ...args, name: text(args.name, "Budget name"), scopeId: text(args.scopeId, "Budget scope"), category: text(args.category, "Budget category"), currency: currency(args.currency), baseAmountMinor: convertToBase(args.amountMinor, args.exchangeRateMicros), status: "approved", createdByUserId: actor.userId, createdAt: now, updatedAt: now }); },
});

export const createInvoice = mutation({
  args: { organizationId: v.string(), clientId: v.id("clients"), engagementId: v.optional(v.id("engagements")), projectId: v.optional(v.id("projects")), issueAt: v.number(), dueAt: v.number(), currency: v.string(), exchangeRateMicros: v.number(), lines: v.array(lineInput) }, returns: v.id("financeInvoices"),
  handler: async (ctx, args) => {
    const actor = await financeAccess(ctx, args.organizationId, "create"); await requireFinanceSettings(ctx, args.organizationId); if (args.dueAt < args.issueAt) throw financeError("INVALID_INVOICE_DATES", "Invoice due date cannot precede issue date."); if (!args.lines.length) throw financeError("INVOICE_LINES_REQUIRED", "Invoice requires at least one line.");
    const client = await ctx.db.get(args.clientId); if (!client || client.organizationId !== args.organizationId || client.deletedAt) throw financeError("CLIENT_NOT_FOUND", "Client was not found."); await validateDimensions(ctx, args.organizationId, args.projectId, args.engagementId);
    const calculated = await Promise.all(args.lines.map((line) => calculateLine(ctx, args.organizationId, args.issueAt, line))); const subtotalMinor = sum(calculated, "netMinor"); const taxMinor = sum(calculated, "taxMinor"); const totalMinor = sum(calculated, "totalMinor");
    const settings = await requireFinanceSettings(ctx, args.organizationId); const now = Date.now(); const number = `${settings.invoicePrefix}-${String(settings.nextInvoiceNumber).padStart(6, "0")}`;
    const invoiceId = await ctx.db.insert("financeInvoices", { organizationId: args.organizationId, number, status: "draft", clientId: args.clientId, engagementId: args.engagementId, projectId: args.projectId, issueAt: args.issueAt, dueAt: args.dueAt, currency: currency(args.currency), subtotalMinor, taxMinor, totalMinor, baseTotalMinor: convertToBase(totalMinor, args.exchangeRateMicros), paidMinor: 0, exchangeRateMicros: args.exchangeRateMicros, createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    await Promise.all(calculated.map((line, order) => ctx.db.insert("financeInvoiceLines", { organizationId: args.organizationId, invoiceId, description: line.input.description.trim(), quantity: line.input.quantity, unitAmountMinor: line.input.unitAmountMinor, netMinor: line.netMinor, taxMinor: line.taxMinor, totalMinor: line.totalMinor, taxRuleId: line.input.taxRuleId, order, clientId: args.clientId, engagementId: line.input.engagementId ?? args.engagementId, projectId: line.input.projectId ?? args.projectId, serviceKey: line.input.serviceKey?.trim(), createdByUserId: actor.userId, createdAt: now, updatedAt: now })));
    await ctx.db.patch(settings._id, { nextInvoiceNumber: settings.nextInvoiceNumber + 1, updatedAt: now }); const invoice = await ctx.db.get(invoiceId); if (invoice) await invoiceSearchProjection(ctx, invoice); return invoiceId;
  },
});

export const postInvoice = mutation({
  args: { organizationId: v.string(), invoiceId: v.id("financeInvoices") }, returns: v.id("financeJournalEntries"),
  handler: async (ctx, args) => {
    const actor = await financeAccess(ctx, args.organizationId, "update"); const invoice = await requireInvoice(ctx, args.organizationId, args.invoiceId); if (invoice.status !== "draft" && invoice.status !== "approved") throw financeError("INVOICE_NOT_POSTABLE", "Only draft or approved invoices can be posted.");
    const [ar, revenue, tax] = await Promise.all([systemAccount(ctx, args.organizationId, "accounts_receivable"), systemAccount(ctx, args.organizationId, "revenue"), systemAccount(ctx, args.organizationId, "tax_payable")]);
    const taxBase = convertToBase(invoice.taxMinor, invoice.exchangeRateMicros); const revenueBase = invoice.baseTotalMinor - taxBase; const dims = await accountingDimensions(ctx, args.organizationId, invoice);
    const lines: LedgerLineInput[] = [{ accountId: ar._id, currency: invoice.currency, debitMinor: invoice.totalMinor, creditMinor: 0, debitBaseMinor: invoice.baseTotalMinor, creditBaseMinor: 0, ...dims }, { accountId: revenue._id, currency: invoice.currency, debitMinor: 0, creditMinor: invoice.subtotalMinor, debitBaseMinor: 0, creditBaseMinor: revenueBase, ...dims }];
    if (invoice.taxMinor) lines.push({ accountId: tax._id, currency: invoice.currency, debitMinor: 0, creditMinor: invoice.taxMinor, debitBaseMinor: 0, creditBaseMinor: taxBase, ...dims });
    const journalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: invoice.issueAt, description: `Post invoice ${invoice.number}`, sourceType: "invoice", sourceId: String(invoice._id), actorUserId: actor.userId, lines }); const now = Date.now(); await ctx.db.patch(invoice._id, { status: "posted", journalEntryId: journalId, postedAt: now, updatedAt: now }); const updated = await ctx.db.get(invoice._id); if (updated) await invoiceSearchProjection(ctx, updated); await emitAutomationEvent(ctx, { organizationId: args.organizationId, eventType: "invoice.posted", resourceType: "invoice", resourceId: String(invoice._id), payload: { journalEntryId: String(journalId), clientId: String(invoice.clientId) }, actorUserId: actor.userId }); return journalId;
  },
});

export const createInvoiceFromTime = mutation({
  args: { organizationId: v.string(), engagementId: v.id("engagements"), timeEntryIds: v.array(v.id("deliveryTimeEntries")), issueAt: v.number(), dueAt: v.number(), currency: v.string(), exchangeRateMicros: v.number() }, returns: v.id("financeInvoices"),
  handler: async (ctx, args) => {
    const actor = await financeAccess(ctx, args.organizationId, "create"); if (!args.timeEntryIds.length) throw financeError("TIME_ENTRIES_REQUIRED", "Select at least one approved time entry."); if (args.dueAt < args.issueAt) throw financeError("INVALID_INVOICE_DATES", "Invoice due date cannot precede issue date."); const engagement = await ctx.db.get(args.engagementId); if (!engagement || engagement.organizationId !== args.organizationId || engagement.deletedAt) throw financeError("ENGAGEMENT_NOT_FOUND", "Engagement was not found.");
    const entries = await Promise.all(args.timeEntryIds.map((id) => ctx.db.get(id))); const unique = new Set(args.timeEntryIds.map(String)); if (unique.size !== args.timeEntryIds.length) throw financeError("DUPLICATE_TIME_ENTRY", "A time entry can appear only once.");
    const priced = [];
    for (const entry of entries) { if (!entry || entry.organizationId !== args.organizationId || entry.engagementId !== engagement._id || entry.status !== "approved" || !entry.billable || !entry.rateCardEntryId) throw financeError("TIME_ENTRY_NOT_BILLABLE", "Every time entry must be approved, billable, priced, and belong to the Engagement."); const rate = await ctx.db.get(entry.rateCardEntryId); if (!rate || rate.organizationId !== args.organizationId || rate.deletedAt) throw financeError("RATE_ENTRY_INVALID", "Time entry rate is unavailable."); const card = await ctx.db.get(rate.rateCardId); if (!card || card.organizationId !== args.organizationId || !card.active || card.currency !== currency(args.currency)) throw financeError("RATE_CARD_CURRENCY_MISMATCH", "Rate card and Invoice currency must match."); const amount = Math.round((entry.minutes * rate.billRateMinor) / 60); priced.push({ entry, amount }); }
    const settings = await requireFinanceSettings(ctx, args.organizationId); const now = Date.now(); const totalMinor = priced.reduce((sum, item) => sum + item.amount, 0); const number = `${settings.invoicePrefix}-${String(settings.nextInvoiceNumber).padStart(6, "0")}`;
    const invoiceId = await ctx.db.insert("financeInvoices", { organizationId: args.organizationId, number, status: "draft", clientId: engagement.clientId, engagementId: engagement._id, issueAt: args.issueAt, dueAt: args.dueAt, currency: currency(args.currency), subtotalMinor: totalMinor, taxMinor: 0, totalMinor, baseTotalMinor: convertToBase(totalMinor, args.exchangeRateMicros), paidMinor: 0, exchangeRateMicros: args.exchangeRateMicros, createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    await Promise.all(priced.map(async ({ entry, amount }, order) => { await ctx.db.insert("financeInvoiceLines", { organizationId: args.organizationId, invoiceId, description: `${entry.description ?? "Billable time"} · ${entry.minutes} minutes`, quantity: 1, unitAmountMinor: amount, netMinor: amount, taxMinor: 0, totalMinor: amount, timeEntryId: entry._id, order, clientId: engagement.clientId, engagementId: engagement._id, projectId: entry.projectId, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); await ctx.db.patch(entry._id, { status: "invoiced", invoiceId, updatedAt: now }); })); await ctx.db.patch(settings._id, { nextInvoiceNumber: settings.nextInvoiceNumber + 1, updatedAt: now }); const invoice = await ctx.db.get(invoiceId); if (invoice) await invoiceSearchProjection(ctx, invoice); return invoiceId;
  },
});

export const recordInvoicePayment = mutation({
  args: { organizationId: v.string(), invoiceId: v.id("financeInvoices"), amountMinor: v.number(), exchangeRateMicros: v.number(), receivedAt: v.number(), method: v.string(), reference: v.optional(v.string()), bankAccountId: v.optional(v.id("financeBankAccounts")) }, returns: v.id("financePayments"),
  handler: async (ctx, args) => {
    const actor = await financeAccess(ctx, args.organizationId, "create"); const invoice = await requireInvoice(ctx, args.organizationId, args.invoiceId); if (!["posted", "partially_paid"].includes(invoice.status)) throw financeError("INVOICE_NOT_PAYABLE", "Invoice must be posted before payment."); positive(args.amountMinor, "Payment"); if (invoice.paidMinor + args.amountMinor > invoice.totalMinor) throw financeError("PAYMENT_EXCEEDS_BALANCE", "Payment exceeds the invoice balance.");
    const [cash, ar, fx] = await Promise.all([bankLedgerAccount(ctx, args.organizationId, args.bankAccountId), systemAccount(ctx, args.organizationId, "accounts_receivable"), systemAccount(ctx, args.organizationId, "fx_gain_loss")]); const cashBase = convertToBase(args.amountMinor, args.exchangeRateMicros); const arBase = convertToBase(args.amountMinor, invoice.exchangeRateMicros); const dims = await accountingDimensions(ctx, args.organizationId, invoice);
    const lines: LedgerLineInput[] = [{ accountId: cash._id, currency: invoice.currency, debitMinor: args.amountMinor, creditMinor: 0, debitBaseMinor: cashBase, creditBaseMinor: 0, ...dims }, { accountId: ar._id, currency: invoice.currency, debitMinor: 0, creditMinor: args.amountMinor, debitBaseMinor: 0, creditBaseMinor: arBase, ...dims }];
    if (cashBase > arBase) lines.push({ accountId: fx._id, currency: invoice.currency, debitMinor: 0, creditMinor: 0, debitBaseMinor: 0, creditBaseMinor: cashBase - arBase, ...dims }); else if (arBase > cashBase) lines.push({ accountId: fx._id, currency: invoice.currency, debitMinor: 0, creditMinor: 0, debitBaseMinor: arBase - cashBase, creditBaseMinor: 0, ...dims });
    const journalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: args.receivedAt, description: `Payment for ${invoice.number}`, sourceType: "invoice_payment", sourceId: String(invoice._id), actorUserId: actor.userId, lines }); const now = Date.now();
    const paymentId = await ctx.db.insert("financePayments", { organizationId: args.organizationId, direction: "inbound", status: "recorded", receivedOrPaidAt: args.receivedAt, method: text(args.method, "Payment method"), reference: args.reference?.trim(), clientId: invoice.clientId, bankAccountId: args.bankAccountId, currency: invoice.currency, amountMinor: args.amountMinor, baseCurrency: (await requireFinanceSettings(ctx, args.organizationId)).baseCurrency, baseAmountMinor: cashBase, exchangeRateMicros: args.exchangeRateMicros, journalEntryId: journalId, createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    await ctx.db.insert("financePaymentApplications", { organizationId: args.organizationId, paymentId, invoiceId: invoice._id, amountMinor: args.amountMinor, baseAmountMinor: arBase, createdByUserId: actor.userId, createdAt: now }); const paidMinor = invoice.paidMinor + args.amountMinor; await ctx.db.patch(invoice._id, { paidMinor, status: paidMinor === invoice.totalMinor ? "paid" : "partially_paid", updatedAt: now }); const [payment, updatedInvoice] = await Promise.all([ctx.db.get(paymentId), ctx.db.get(invoice._id)]); if (payment) await paymentSearchProjection(ctx, payment); if (updatedInvoice) await invoiceSearchProjection(ctx, updatedInvoice); await emitAutomationEvent(ctx, { organizationId: args.organizationId, eventType: "payment.recorded", resourceType: "payment", resourceId: String(paymentId), payload: { invoiceId: String(invoice._id), clientId: String(invoice.clientId) }, actorUserId: actor.userId }); return paymentId;
  },
});

export const createExpense = mutation({
  args: { organizationId: v.string(), description: v.string(), incurredAt: v.number(), dueAt: v.optional(v.number()), vendorId: v.optional(v.id("financeVendors")), projectId: v.optional(v.id("projects")), engagementId: v.optional(v.id("engagements")), clientId: v.optional(v.id("clients")), currency: v.string(), amountMinor: v.number(), exchangeRateMicros: v.number(), taxRuleId: v.optional(v.id("financeTaxRules")) }, returns: v.id("financeExpenses"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); positive(args.amountMinor, "Expense"); await validateDimensions(ctx, args.organizationId, args.projectId, args.engagementId); const expenseAccount = await systemAccount(ctx, args.organizationId, "expense"); const tax = args.taxRuleId ? await requireTax(ctx, args.organizationId, args.taxRuleId, args.incurredAt) : null; const calculation = tax ? calculateTax(args.amountMinor, tax.exempt ? 0 : tax.rateBasisPoints, tax.calculation) : { netMinor: args.amountMinor, taxMinor: 0, totalMinor: args.amountMinor }; const now = Date.now(); const id = await ctx.db.insert("financeExpenses", { organizationId: args.organizationId, vendorId: args.vendorId, description: text(args.description, "Expense description"), status: "approved", incurredAt: args.incurredAt, dueAt: args.dueAt, expenseAccountId: expenseAccount._id, taxRuleId: args.taxRuleId, currency: currency(args.currency), amountMinor: calculation.totalMinor, baseCurrency: (await requireFinanceSettings(ctx, args.organizationId)).baseCurrency, baseAmountMinor: convertToBase(calculation.totalMinor, args.exchangeRateMicros), exchangeRateMicros: args.exchangeRateMicros, taxMinor: calculation.taxMinor, baseTaxMinor: convertToBase(calculation.taxMinor, args.exchangeRateMicros), clientId: args.clientId, engagementId: args.engagementId, projectId: args.projectId, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); const expense = await ctx.db.get(id); if (expense) await expenseSearchProjection(ctx, expense); return id; },
});

export const createVendor = mutation({
  args: { organizationId: v.string(), name: v.string(), currency: v.string(), taxIdentifier: v.optional(v.string()) }, returns: v.id("financeVendors"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); const now = Date.now(); return ctx.db.insert("financeVendors", { organizationId: args.organizationId, name: text(args.name, "Vendor name"), currency: currency(args.currency), taxIdentifier: args.taxIdentifier?.trim(), active: true, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); },
});

export const payExpense = mutation({
  args: { organizationId: v.string(), expenseId: v.id("financeExpenses"), paidAt: v.number(), exchangeRateMicros: v.number(), method: v.string(), reference: v.optional(v.string()), bankAccountId: v.optional(v.id("financeBankAccounts")) }, returns: v.id("financePayments"),
  handler: async (ctx, args) => {
    const actor = await financeAccess(ctx, args.organizationId, "create"); const expense = await requireExpense(ctx, args.organizationId, args.expenseId); if (expense.status !== "posted" || expense.paymentId) throw financeError("EXPENSE_NOT_PAYABLE", "Expense must be posted and unpaid.");
    const [cash, ap, fx] = await Promise.all([bankLedgerAccount(ctx, args.organizationId, args.bankAccountId), systemAccount(ctx, args.organizationId, "accounts_payable"), systemAccount(ctx, args.organizationId, "fx_gain_loss")]); const cashBase = convertToBase(expense.amountMinor, args.exchangeRateMicros); const apBase = expense.baseAmountMinor; const dims = await accountingDimensions(ctx, args.organizationId, expense);
    const lines: LedgerLineInput[] = [{ accountId: ap._id, currency: expense.currency, debitMinor: expense.amountMinor, creditMinor: 0, debitBaseMinor: apBase, creditBaseMinor: 0, ...dims }, { accountId: cash._id, currency: expense.currency, debitMinor: 0, creditMinor: expense.amountMinor, debitBaseMinor: 0, creditBaseMinor: cashBase, ...dims }];
    if (cashBase > apBase) lines.push({ accountId: fx._id, currency: expense.currency, debitMinor: 0, creditMinor: 0, debitBaseMinor: cashBase - apBase, creditBaseMinor: 0, ...dims }); else if (apBase > cashBase) lines.push({ accountId: fx._id, currency: expense.currency, debitMinor: 0, creditMinor: 0, debitBaseMinor: 0, creditBaseMinor: apBase - cashBase, ...dims });
    const journalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: args.paidAt, description: `Pay expense ${expense.description}`, sourceType: "expense_payment", sourceId: String(expense._id), actorUserId: actor.userId, lines }); const now = Date.now(); const settings = await requireFinanceSettings(ctx, args.organizationId);
    const paymentId = await ctx.db.insert("financePayments", { organizationId: args.organizationId, direction: "outbound", status: "recorded", receivedOrPaidAt: args.paidAt, method: text(args.method, "Payment method"), reference: args.reference?.trim(), vendorId: expense.vendorId, bankAccountId: args.bankAccountId, currency: expense.currency, amountMinor: expense.amountMinor, baseCurrency: settings.baseCurrency, baseAmountMinor: cashBase, exchangeRateMicros: args.exchangeRateMicros, journalEntryId: journalId, createdByUserId: actor.userId, createdAt: now, updatedAt: now });
    await ctx.db.insert("financePaymentApplications", { organizationId: args.organizationId, paymentId, expenseId: expense._id, amountMinor: expense.amountMinor, baseAmountMinor: apBase, createdByUserId: actor.userId, createdAt: now }); await ctx.db.patch(expense._id, { status: "paid", paymentId, updatedAt: now }); const [payment, updatedExpense] = await Promise.all([ctx.db.get(paymentId), ctx.db.get(expense._id)]); if (payment) await paymentSearchProjection(ctx, payment); if (updatedExpense) await expenseSearchProjection(ctx, updatedExpense); return paymentId;
  },
});

export const createEstimate = mutation({
  args: { organizationId: v.string(), title: v.string(), clientId: v.id("clients"), engagementId: v.optional(v.id("engagements")), projectId: v.optional(v.id("projects")), currency: v.string(), exchangeRateMicros: v.number(), validUntil: v.optional(v.number()), lines: v.array(lineInput) }, returns: v.id("financeEstimates"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); if (!args.lines.length) throw financeError("ESTIMATE_LINES_REQUIRED", "Estimate requires at least one line."); const client = await ctx.db.get(args.clientId); if (!client || client.organizationId !== args.organizationId || client.deletedAt) throw financeError("CLIENT_NOT_FOUND", "Client was not found."); await validateDimensions(ctx, args.organizationId, args.projectId, args.engagementId); const now = Date.now(); const calculated = await Promise.all(args.lines.map((line) => calculateLine(ctx, args.organizationId, now, line))); const subtotalMinor = sum(calculated, "netMinor"); const taxMinor = sum(calculated, "taxMinor"); const totalMinor = sum(calculated, "totalMinor"); const id = await ctx.db.insert("financeEstimates", { organizationId: args.organizationId, number: `EST-${now}`, title: text(args.title, "Estimate title"), status: "draft", clientId: args.clientId, engagementId: args.engagementId, projectId: args.projectId, currency: currency(args.currency), subtotalMinor, taxMinor, totalMinor, baseTotalMinor: convertToBase(totalMinor, args.exchangeRateMicros), exchangeRateMicros: args.exchangeRateMicros, validUntil: args.validUntil, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); await Promise.all(calculated.map((line, order) => ctx.db.insert("financeEstimateLines", { organizationId: args.organizationId, estimateId: id, description: line.input.description.trim(), quantity: line.input.quantity, unitAmountMinor: line.input.unitAmountMinor, netMinor: line.netMinor, taxMinor: line.taxMinor, totalMinor: line.totalMinor, taxRuleId: line.input.taxRuleId, order, clientId: args.clientId, engagementId: line.input.engagementId ?? args.engagementId, projectId: line.input.projectId ?? args.projectId, serviceKey: line.input.serviceKey?.trim(), createdByUserId: actor.userId, createdAt: now, updatedAt: now }))); return id; },
});

export const acceptEstimate = mutation({
  args: { organizationId: v.string(), estimateId: v.id("financeEstimates") }, returns: v.null(),
  handler: async (ctx, args) => { await financeAccess(ctx, args.organizationId, "update"); const estimate = await ctx.db.get(args.estimateId); if (!estimate || estimate.organizationId !== args.organizationId || estimate.deletedAt || !["draft", "sent"].includes(estimate.status)) throw financeError("ESTIMATE_NOT_ACCEPTABLE", "Estimate is unavailable or cannot be accepted."); const now = Date.now(); if (estimate.validUntil && estimate.validUntil < now) throw financeError("ESTIMATE_EXPIRED", "Estimate has expired."); await ctx.db.patch(estimate._id, { status: "accepted", acceptedAt: now, updatedAt: now }); return null; },
});

export const receiveRetainer = mutation({
  args: { organizationId: v.string(), engagementId: v.id("engagements"), amountMinor: v.number(), exchangeRateMicros: v.number(), receivedAt: v.number(), method: v.string(), bankAccountId: v.optional(v.id("financeBankAccounts")) }, returns: v.id("financeRetainers"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); positive(args.amountMinor, "Retainer"); const engagement = await ctx.db.get(args.engagementId); if (!engagement || engagement.organizationId !== args.organizationId || engagement.deletedAt) throw financeError("ENGAGEMENT_NOT_FOUND", "Engagement was not found."); const [cash, liability] = await Promise.all([bankLedgerAccount(ctx, args.organizationId, args.bankAccountId), systemAccount(ctx, args.organizationId, "retainer_liability")]); const base = convertToBase(args.amountMinor, args.exchangeRateMicros); const dims = dimensions(engagement); const journalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: args.receivedAt, description: `Receive retainer for ${engagement.name}`, sourceType: "retainer_receipt", sourceId: String(engagement._id), actorUserId: actor.userId, lines: [{ accountId: cash._id, currency: engagement.currency, debitMinor: args.amountMinor, creditMinor: 0, debitBaseMinor: base, creditBaseMinor: 0, ...dims }, { accountId: liability._id, currency: engagement.currency, debitMinor: 0, creditMinor: args.amountMinor, debitBaseMinor: 0, creditBaseMinor: base, ...dims }] }); const now = Date.now(); const settings = await requireFinanceSettings(ctx, args.organizationId); const paymentId = await ctx.db.insert("financePayments", { organizationId: args.organizationId, direction: "inbound", status: "recorded", receivedOrPaidAt: args.receivedAt, method: text(args.method, "Payment method"), clientId: engagement.clientId, bankAccountId: args.bankAccountId, currency: engagement.currency, amountMinor: args.amountMinor, baseCurrency: settings.baseCurrency, baseAmountMinor: base, exchangeRateMicros: args.exchangeRateMicros, journalEntryId: journalId, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); return ctx.db.insert("financeRetainers", { organizationId: args.organizationId, engagementId: engagement._id, clientId: engagement.clientId, paymentId, currency: engagement.currency, receivedMinor: args.amountMinor, appliedMinor: 0, baseReceivedMinor: base, exchangeRateMicros: args.exchangeRateMicros, status: "active", createdByUserId: actor.userId, createdAt: now, updatedAt: now }); },
});

export const applyRetainer = mutation({
  args: { organizationId: v.string(), retainerId: v.id("financeRetainers"), invoiceId: v.id("financeInvoices"), amountMinor: v.number(), accountingDate: v.number() }, returns: v.id("financeJournalEntries"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "update"); positive(args.amountMinor, "Retainer application"); const [retainer, invoice] = await Promise.all([ctx.db.get(args.retainerId), requireInvoice(ctx, args.organizationId, args.invoiceId)]); if (!retainer || retainer.organizationId !== args.organizationId || retainer.deletedAt || retainer.status !== "active") throw financeError("RETAINER_NOT_AVAILABLE", "Retainer is unavailable."); if (retainer.clientId !== invoice.clientId || retainer.currency !== invoice.currency) throw financeError("RETAINER_INVOICE_MISMATCH", "Retainer and Invoice must have the same Client and currency."); if (args.amountMinor > retainer.receivedMinor - retainer.appliedMinor || args.amountMinor > invoice.totalMinor - invoice.paidMinor) throw financeError("RETAINER_AMOUNT_EXCEEDS_BALANCE", "Retainer application exceeds an available balance."); const [liability, ar] = await Promise.all([systemAccount(ctx, args.organizationId, "retainer_liability"), systemAccount(ctx, args.organizationId, "accounts_receivable")]); const base = convertToBase(args.amountMinor, retainer.exchangeRateMicros); const dims = dimensions(invoice); const journalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: args.accountingDate, description: `Apply retainer to ${invoice.number}`, sourceType: "retainer_application", sourceId: String(retainer._id), actorUserId: actor.userId, lines: [{ accountId: liability._id, currency: invoice.currency, debitMinor: args.amountMinor, creditMinor: 0, debitBaseMinor: base, creditBaseMinor: 0, ...dims }, { accountId: ar._id, currency: invoice.currency, debitMinor: 0, creditMinor: args.amountMinor, debitBaseMinor: 0, creditBaseMinor: base, ...dims }] }); const now = Date.now(); await ctx.db.insert("financePaymentApplications", { organizationId: args.organizationId, paymentId: retainer.paymentId, invoiceId: invoice._id, retainerId: retainer._id, amountMinor: args.amountMinor, baseAmountMinor: base, createdByUserId: actor.userId, createdAt: now }); const appliedMinor = retainer.appliedMinor + args.amountMinor; await ctx.db.patch(retainer._id, { appliedMinor, status: appliedMinor === retainer.receivedMinor ? "exhausted" : "active", updatedAt: now }); const paidMinor = invoice.paidMinor + args.amountMinor; await ctx.db.patch(invoice._id, { paidMinor, status: paidMinor === invoice.totalMinor ? "paid" : "partially_paid", updatedAt: now }); return journalId; },
});

export const createBankAccount = mutation({
  args: { organizationId: v.string(), name: v.string(), currency: v.string() }, returns: v.id("financeBankAccounts"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "create"); const now = Date.now(); const ledgerAccountId = await ctx.db.insert("financeAccounts", { organizationId: args.organizationId, code: `10${String(now).slice(-4)}`, name: text(args.name, "Bank account name"), type: "asset", currency: currency(args.currency), active: true, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); return ctx.db.insert("financeBankAccounts", { organizationId: args.organizationId, name: text(args.name, "Bank account name"), currency: currency(args.currency), ledgerAccountId, active: true, createdByUserId: actor.userId, createdAt: now, updatedAt: now }); },
});

export const importBankTransaction = mutation({
  args: { organizationId: v.string(), bankAccountId: v.id("financeBankAccounts"), externalId: v.string(), occurredAt: v.number(), description: v.string(), amountMinor: v.number(), currency: v.string() }, returns: v.id("financeBankTransactions"),
  handler: async (ctx, args) => { await financeAccess(ctx, args.organizationId, "create"); const bank = await ctx.db.get(args.bankAccountId); if (!bank || bank.organizationId !== args.organizationId || !bank.active) throw financeError("BANK_ACCOUNT_NOT_FOUND", "Bank account was not found."); const externalId = text(args.externalId, "External transaction ID"); const existing = await ctx.db.query("financeBankTransactions").withIndex("by_external", (q) => q.eq("organizationId", args.organizationId).eq("bankAccountId", args.bankAccountId).eq("externalId", externalId)).unique(); if (existing) return existing._id; const now = Date.now(); return ctx.db.insert("financeBankTransactions", { organizationId: args.organizationId, bankAccountId: bank._id, externalId, occurredAt: args.occurredAt, description: text(args.description, "Transaction description"), amountMinor: args.amountMinor, currency: currency(args.currency), status: "unmatched", createdAt: now, updatedAt: now }); },
});

export const reconcileBankTransaction = mutation({
  args: { organizationId: v.string(), transactionId: v.id("financeBankTransactions"), paymentId: v.id("financePayments") }, returns: v.null(),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "update"); const [transaction, payment] = await Promise.all([ctx.db.get(args.transactionId), ctx.db.get(args.paymentId)]); if (!transaction || transaction.organizationId !== args.organizationId || transaction.status !== "unmatched" || !payment || payment.organizationId !== args.organizationId || payment.status !== "recorded") throw financeError("RECONCILIATION_RECORD_INVALID", "Bank transaction or payment is unavailable."); const expected = payment.direction === "inbound" ? payment.amountMinor : -payment.amountMinor; if (transaction.currency !== payment.currency || transaction.amountMinor !== expected) throw financeError("RECONCILIATION_AMOUNT_MISMATCH", "Bank transaction must match payment amount, direction, and currency."); const now = Date.now(); await ctx.db.patch(transaction._id, { status: "matched", paymentId: payment._id, reconciledByUserId: actor.userId, reconciledAt: now, updatedAt: now }); return null; },
});

export const postExpense = mutation({
  args: { organizationId: v.string(), expenseId: v.id("financeExpenses") }, returns: v.id("financeJournalEntries"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "update"); const expense = await requireExpense(ctx, args.organizationId, args.expenseId); if (expense.status !== "approved") throw financeError("EXPENSE_NOT_POSTABLE", "Only approved expenses can be posted."); const [ap, taxReceivable] = await Promise.all([systemAccount(ctx, args.organizationId, "accounts_payable"), systemAccount(ctx, args.organizationId, "tax_receivable")]); const dims = await accountingDimensions(ctx, args.organizationId, expense); const netMinor = expense.amountMinor - expense.taxMinor; const netBaseMinor = expense.baseAmountMinor - expense.baseTaxMinor; const lines: LedgerLineInput[] = [{ accountId: expense.expenseAccountId, currency: expense.currency, debitMinor: netMinor, creditMinor: 0, debitBaseMinor: netBaseMinor, creditBaseMinor: 0, ...dims }]; if (expense.taxMinor) lines.push({ accountId: taxReceivable._id, currency: expense.currency, debitMinor: expense.taxMinor, creditMinor: 0, debitBaseMinor: expense.baseTaxMinor, creditBaseMinor: 0, ...dims }); lines.push({ accountId: ap._id, currency: expense.currency, debitMinor: 0, creditMinor: expense.amountMinor, debitBaseMinor: 0, creditBaseMinor: expense.baseAmountMinor, ...dims }); const journalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: expense.incurredAt, description: expense.description, sourceType: "expense", sourceId: String(expense._id), actorUserId: actor.userId, lines }); await ctx.db.patch(expense._id, { status: "posted", journalEntryId: journalId, updatedAt: Date.now() }); const updated = await ctx.db.get(expense._id); if (updated) await expenseSearchProjection(ctx, updated); return journalId; },
});

export const closeAccountingPeriod = mutation({
  args: { organizationId: v.string(), periodId: v.id("financeAccountingPeriods") }, returns: v.null(),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "update"); const period = await ctx.db.get(args.periodId); if (!period || period.organizationId !== args.organizationId || period.deletedAt || period.status !== "open") throw financeError("PERIOD_NOT_OPEN", "Accounting period is unavailable or closed."); const now = Date.now(); await ctx.db.patch(period._id, { status: "closed", closedByUserId: actor.userId, closedAt: now, updatedAt: now }); const settings = await requireFinanceSettings(ctx, args.organizationId); if (!settings.lockDate || period.endAt > settings.lockDate) await ctx.db.patch(settings._id, { lockDate: period.endAt, updatedAt: now }); await emitAutomationEvent(ctx, { organizationId: args.organizationId, eventType: "accounting_period.closed", resourceType: "accounting_period", resourceId: String(period._id), payload: { endAt: String(period.endAt) }, actorUserId: actor.userId }); return null; },
});

export const reverseJournal = mutation({
  args: { organizationId: v.string(), journalEntryId: v.id("financeJournalEntries"), accountingDate: v.number(), reason: v.string() }, returns: v.id("financeJournalEntries"),
  handler: async (ctx, args) => { const actor = await financeAccess(ctx, args.organizationId, "update"); const original = await ctx.db.get(args.journalEntryId); if (!original || original.organizationId !== args.organizationId || original.status !== "posted" || original.reversedById) throw financeError("JOURNAL_NOT_REVERSIBLE", "Journal is unavailable or already reversed."); const source = await ctx.db.query("financeLedgerLines").withIndex("by_journal", (q) => q.eq("organizationId", args.organizationId).eq("journalEntryId", original._id)).collect(); const reversalId = await postJournal(ctx, { organizationId: args.organizationId, accountingDate: args.accountingDate, description: text(args.reason, "Reversal reason"), sourceType: "journal_reversal", sourceId: String(original._id), reversalOfId: original._id, actorUserId: actor.userId, lines: source.map((line) => ({ ...dimensions(line), accountId: line.accountId, currency: line.currency, debitMinor: line.creditMinor, creditMinor: line.debitMinor, debitBaseMinor: line.creditBaseMinor, creditBaseMinor: line.debitBaseMinor, description: `Reversal: ${line.description ?? original.description}` })) }); const now = Date.now(); await ctx.db.patch(original._id, { status: "reversed", reversedById: reversalId, updatedAt: now }); return reversalId; },
});

async function calculateLine(ctx: MutationCtx, organizationId: string, date: number, input: { description: string; quantity: number; unitAmountMinor: number; taxRuleId?: Id<"financeTaxRules">; projectId?: Id<"projects">; engagementId?: Id<"engagements">; serviceKey?: string }) { positive(input.quantity, "Quantity"); nonnegative(input.unitAmountMinor, "Unit amount"); text(input.description, "Line description"); await validateDimensions(ctx, organizationId, input.projectId, input.engagementId); const amount = input.quantity * input.unitAmountMinor; if (!Number.isSafeInteger(amount)) throw financeError("LINE_AMOUNT_OVERFLOW", "Invoice line amount is too large."); const tax = input.taxRuleId ? await requireTax(ctx, organizationId, input.taxRuleId, date) : null; return { input, ...calculateTax(amount, tax?.exempt ? 0 : tax?.rateBasisPoints ?? 0, tax?.calculation ?? "exclusive") }; }
async function requireTax(ctx: MutationCtx, organizationId: string, id: Id<"financeTaxRules">, date: number) { const rule = await ctx.db.get(id); if (!rule || rule.organizationId !== organizationId || !rule.active || rule.deletedAt || rule.effectiveFrom > date || (rule.effectiveTo !== undefined && rule.effectiveTo < date)) throw financeError("TAX_RULE_INVALID", "Tax rule is not effective on the transaction date."); return rule; }
async function requireInvoice(ctx: MutationCtx, organizationId: string, id: Id<"financeInvoices">) { const record = await ctx.db.get(id); if (!record || record.organizationId !== organizationId || record.deletedAt) throw financeError("INVOICE_NOT_FOUND", "Invoice was not found."); return record; }
async function requireExpense(ctx: MutationCtx, organizationId: string, id: Id<"financeExpenses">) { const record = await ctx.db.get(id); if (!record || record.organizationId !== organizationId || record.deletedAt) throw financeError("EXPENSE_NOT_FOUND", "Expense was not found."); return record; }
async function bankLedgerAccount(ctx: MutationCtx, organizationId: string, bankAccountId?: Id<"financeBankAccounts">) { if (!bankAccountId) return systemAccount(ctx, organizationId, "cash"); const bank = await ctx.db.get(bankAccountId); if (!bank || bank.organizationId !== organizationId || !bank.active || bank.deletedAt) throw financeError("BANK_ACCOUNT_NOT_FOUND", "Bank account was not found."); const ledger = await ctx.db.get(bank.ledgerAccountId); if (!ledger || ledger.organizationId !== organizationId || !ledger.active) throw financeError("BANK_LEDGER_ACCOUNT_INVALID", "Bank ledger account is unavailable."); return ledger; }
async function validateDimensions(ctx: MutationCtx, organizationId: string, projectId?: Id<"projects">, engagementId?: Id<"engagements">) { if (projectId) { const project = await ctx.db.get(projectId); if (!project || project.organizationId !== organizationId || project.deletedAt) throw financeError("PROJECT_NOT_FOUND", "Project was not found."); } if (engagementId) { const engagement = await ctx.db.get(engagementId); if (!engagement || engagement.organizationId !== organizationId || engagement.deletedAt) throw financeError("ENGAGEMENT_NOT_FOUND", "Engagement was not found."); } }
function dimensions(value: { clientId?: Id<"clients">; engagementId?: Id<"engagements">; projectId?: Id<"projects">; spaceId?: Id<"spaces">; serviceKey?: string }) { return { clientId: value.clientId, engagementId: value.engagementId, projectId: value.projectId, spaceId: value.spaceId, serviceKey: value.serviceKey }; }
async function accountingDimensions(ctx: MutationCtx, organizationId: string, value: { clientId?: Id<"clients">; engagementId?: Id<"engagements">; projectId?: Id<"projects">; spaceId?: Id<"spaces">; serviceKey?: string }) { if (value.spaceId || !value.projectId) return dimensions(value); const link = await ctx.db.query("projectSpaces").withIndex("by_project_primary", (q) => q.eq("organizationId", organizationId).eq("projectId", value.projectId!).eq("isPrimary", true)).unique(); return { ...dimensions(value), spaceId: link && !link.deletedAt ? link.spaceId : undefined }; }
function sum<T extends Record<K, number>, K extends string>(items: T[], key: K) { return items.reduce((total, item) => total + item[key], 0); }
function interval(startAt: number, endAt: number) { if (!Number.isFinite(startAt) || !Number.isFinite(endAt) || endAt <= startAt) throw financeError("INVALID_INTERVAL", "End date must be after start date."); }
function text(value: string, label: string) { const normalized = value.trim(); if (!normalized) throw financeError("REQUIRED_TEXT", `${label} is required.`); return normalized; }
function currency(value: string) { const normalized = value.trim().toUpperCase(); if (!/^[A-Z]{3}$/u.test(normalized)) throw financeError("INVALID_CURRENCY", "Currency must be a three-letter ISO code."); return normalized; }
function positive(value: number, label: string) { if (!Number.isSafeInteger(value) || value <= 0) throw financeError("INVALID_AMOUNT", `${label} must be a positive integer in minor units.`); }
function nonnegative(value: number, label: string) { if (!Number.isSafeInteger(value) || value < 0) throw financeError("INVALID_AMOUNT", `${label} must be a non-negative integer.`); }
