import type { NavigationDomainId, NavigationNode } from "@qentrah/domain-contracts";
import type { Resource } from "../permissions";

export type NavigationCatalogDomain = Readonly<{
  id: NavigationDomainId;
  labelKey: string;
  iconId: string;
  routeId: string;
  required: boolean;
  opensPanel: boolean;
  readResources: readonly Resource[];
  accessMode?: "any" | "all";
  requiredAction?: "read" | "update";
  nodes: readonly NavigationNode[];
}>;

function node(
  domainId: NavigationDomainId,
  id: string,
  labelKey: string,
  iconId: string,
  routeId: string,
  options: { params?: Record<string, string>; required?: boolean } = {},
): NavigationNode {
  return {
    id,
    domainId,
    labelKey,
    iconId,
    routeId,
    params: options.params,
    nodeType: "route",
    required: options.required ?? false,
    opensPanel: false,
  };
}

/** Canonical product order. Rollout and authorization decide which domains reach a caller. */
export const IMPLEMENTED_NAVIGATION_CATALOG: readonly NavigationCatalogDomain[] = [
  {
    id: "home", labelKey: "home", iconId: "home", routeId: "ws", required: true, opensPanel: true, readResources: ["organization"],
    nodes: [
      node("home", "home.overview", "overview", "overview", "ws", { required: true }),
      node("home", "home.my-work", "myWork", "my-work", "tasks", { params: { filter: "my" }, required: true }),
      node("home", "home.attention", "needsAttention", "attention", "inbox"),
      node("home", "home.approvals", "approvalsWaiting", "inbox", "delivery", { params: { view: "approvals" } }),
      node("home", "home.deadlines", "upcomingDeadlines", "upcoming", "tasks", { params: { filter: "upcoming" } }),
      node("home", "home.recent", "recent", "recent", "search", { params: { view: "recent" } }),
      node("home", "home.favorites", "favorites", "completed", "projects", { params: { filter: "favorites" } }),
      node("home", "home.dashboards", "personalDashboards", "overview", "ws", { params: { view: "dashboards" } }),
    ],
  },
  {
    id: "inbox", labelKey: "inbox", iconId: "inbox", routeId: "inbox", required: true, opensPanel: true, readResources: ["channel"],
    nodes: [
      node("inbox", "inbox.primary", "primary", "inbox", "inbox", { required: true }),
      node("inbox", "inbox.mentions", "mentions", "attention", "inbox", { params: { filter: "mentions" } }),
      node("inbox", "inbox.assigned", "assignedToMe", "assigned", "tasks", { params: { filter: "assigned-to-me" } }),
      node("inbox", "inbox.approvals", "approvalRequests", "inbox", "delivery", { params: { view: "approvals" } }),
      node("inbox", "inbox.followups", "followUps", "upcoming", "inbox", { params: { filter: "follow-ups" } }),
      node("inbox", "inbox.saved", "saved", "completed", "inbox", { params: { filter: "saved" } }),
      node("inbox", "inbox.channels", "channels", "channels", "channels", { required: true }),
      node("inbox", "inbox.direct", "directConversations", "members", "channels", { params: { type: "dm" } }),
      node("inbox", "inbox.team-channels", "teamChannels", "members", "channels", { params: { type: "team" } }),
      node("inbox", "inbox.space-channels", "spaceChannels", "spaces", "channels", { params: { type: "space" } }),
      node("inbox", "inbox.project-channels", "projectChannels", "projects", "channels", { params: { type: "project" } }),
    ],
  },
  {
    id: "projects", labelKey: "projects", iconId: "projects", routeId: "projects", required: true, opensPanel: true, readResources: ["project"],
    nodes: [
      node("projects", "projects.portfolio", "portfolio", "overview", "projects", { params: { view: "portfolio" }, required: true }),
      node("projects", "projects.all", "allProjects", "projects", "projects", { required: true }),
      node("projects", "projects.mine", "myProjects", "my-work", "projects", { params: { filter: "my" } }),
      node("projects", "projects.risk", "atRisk", "attention", "projects", { params: { filter: "at-risk" } }),
      node("projects", "projects.recent", "recentlyUpdated", "recent", "projects", { params: { sort: "updated" } }),
      node("projects", "projects.templates", "templates", "templates", "projects", { params: { view: "templates" } }),
      node("projects", "projects.archived", "archived", "recent", "projects", { params: { filter: "archived" } }),
    ],
  },
  {
    id: "tasks", labelKey: "tasks", iconId: "tasks", routeId: "tasks", required: true, opensPanel: true, readResources: ["task"],
    nodes: [
      node("tasks", "tasks.all", "allTasks", "tasks", "tasks", { required: true }),
      node("tasks", "tasks.mine", "myTasks", "my-work", "tasks", { params: { filter: "my" } }),
      node("tasks", "tasks.assigned-by-me", "assignedByMe", "assigned", "tasks", { params: { filter: "assigned" } }),
      node("tasks", "tasks.created-by-me", "createdByMe", "my-work", "tasks", { params: { filter: "created" } }),
      node("tasks", "tasks.unassigned", "unassigned", "unassigned", "tasks", { params: { filter: "unassigned" } }),
      node("tasks", "tasks.overdue", "overdue", "overdue", "tasks", { params: { filter: "overdue" } }),
      node("tasks", "tasks.upcoming", "upcoming", "upcoming", "tasks", { params: { filter: "upcoming" } }),
      node("tasks", "tasks.completed", "completed", "completed", "tasks", { params: { filter: "completed" } }),
      node("tasks", "tasks.saved-views", "savedViews", "overview", "tasks", { params: { view: "saved" } }),
      node("tasks", "tasks.forms", "forms", "docs", "tasks", { params: { view: "form" } }),
      node("tasks", "tasks.templates", "templates", "templates", "tasks", { params: { view: "templates" } }),
    ],
  },
  {
    id: "docs", labelKey: "docs", iconId: "docs", routeId: "docs", required: true, opensPanel: true, readResources: ["document"],
    nodes: [
      node("docs", "docs.all", "allDocs", "docs", "docs", { required: true }),
      node("docs", "docs.mine", "myDocuments", "my-work", "docs", { params: { filter: "my" } }),
      node("docs", "docs.shared", "sharedWithMe", "shared", "docs", { params: { filter: "shared" } }),
      node("docs", "docs.recent", "recent", "recent", "docs", { params: { filter: "recent" } }),
      node("docs", "docs.favorites", "favorites", "completed", "docs", { params: { filter: "favorites" } }),
      node("docs", "docs.templates", "templates", "templates", "docs", { params: { template: "true" } }),
      node("docs", "docs.folders", "folders", "spaces", "docs", { params: { view: "folders" } }),
      node("docs", "docs.space", "spaceDocuments", "spaces", "docs", { params: { scope: "space" } }),
      node("docs", "docs.project", "projectDocuments", "projects", "docs", { params: { scope: "project" } }),
      node("docs", "docs.client", "clientDocuments", "clients", "docs", { params: { scope: "client" } }),
      node("docs", "docs.archived", "archived", "recent", "docs", { params: { filter: "archived" } }),
    ],
  },
  {
    id: "calendar", labelKey: "calendar", iconId: "calendar", routeId: "calendar", required: true, opensPanel: true, readResources: ["calendar"],
    nodes: [
      node("calendar", "calendar.mine", "myCalendar", "calendar", "calendar", { required: true }),
      node("calendar", "calendar.team", "teamCalendar", "members", "calendar", { params: { view: "team" } }),
      node("calendar", "calendar.spaces", "spaceCalendars", "spaces", "calendar", { params: { view: "spaces" } }),
      node("calendar", "calendar.projects", "projectCalendars", "projects", "calendar", { params: { view: "projects" } }),
      node("calendar", "calendar.milestones", "milestones", "completed", "calendar", { params: { view: "milestones" } }),
      node("calendar", "calendar.delivery", "deliveryDeadlines", "delivery", "calendar", { params: { view: "delivery" } }),
      node("calendar", "calendar.meetings", "clientMeetings", "clients", "calendar", { params: { view: "client-meetings" } }),
      node("calendar", "calendar.leave", "timeOff", "calendar", "calendar", { params: { view: "leave" } }),
      node("calendar", "calendar.saved", "savedCalendarViews", "overview", "calendar", { params: { view: "saved" } }),
    ],
  },
  {
    id: "crm", labelKey: "crm", iconId: "crm", routeId: "clients", required: true, opensPanel: true, readResources: ["client", "deal"], accessMode: "any",
    nodes: [
      node("crm", "crm.overview", "crmOverview", "overview", "clients", { params: { view: "overview" }, required: true }),
      node("crm", "crm.leads", "leads", "attention", "leads", { required: true }),
      node("crm", "crm.clients", "clients", "clients", "clients", { required: true }),
      node("crm", "crm.contacts", "contacts", "members", "contacts"),
      node("crm", "crm.companies", "companies", "organization", "companies"),
      node("crm", "crm.deals", "deals", "deals", "deals", { required: true }),
      node("crm", "crm.pipeline", "pipeline", "deals", "deals", { params: { view: "pipeline" } }),
      node("crm", "crm.proposals", "proposals", "docs", "proposals"),
      node("crm", "crm.contracts", "contracts", "docs", "contracts"),
      node("crm", "crm.followups", "followUps", "upcoming", "clients", { params: { view: "follow-ups" } }),
      node("crm", "crm.activities", "crmActivities", "recent", "clients", { params: { view: "activities" } }),
      node("crm", "crm.reports", "crmReports", "reports", "reports", { params: { view: "sales" } }),
      node("crm", "crm.configuration", "configuration", "admin", "clients", { params: { view: "configuration" } }),
      node("crm", "crm.config.pipelines", "pipelines", "deals", "clients", { params: { config: "pipelines" } }),
      node("crm", "crm.config.stages", "stages", "completed", "clients", { params: { config: "stages" } }),
      node("crm", "crm.config.loss-reasons", "lossReasons", "attention", "clients", { params: { config: "loss-reasons" } }),
      node("crm", "crm.config.lead-sources", "leadSources", "attention", "clients", { params: { config: "lead-sources" } }),
      node("crm", "crm.config.custom-fields", "customFields", "tags", "clients", { params: { config: "custom-fields" } }),
      node("crm", "crm.config.templates", "templates", "templates", "clients", { params: { config: "templates" } }),
    ],
  },
  {
    id: "delivery", labelKey: "delivery", iconId: "delivery", routeId: "delivery", required: true, opensPanel: true, readResources: ["project"],
    nodes: [
      node("delivery", "delivery.overview", "deliveryOverview", "overview", "delivery", { required: true }),
      node("delivery", "delivery.engagements", "engagements", "projects", "delivery", { required: true }),
      node("delivery", "delivery.active", "activeDelivery", "attention", "delivery", { params: { status: "active" } }),
      node("delivery", "delivery.retainers", "retainers", "billing", "delivery", { params: { view: "retainers" } }),
      node("delivery", "delivery.milestones", "milestones", "completed", "delivery", { params: { view: "milestones" } }),
      node("delivery", "delivery.deliverables", "deliverables", "tasks", "delivery", { params: { view: "deliverables" } }),
      node("delivery", "delivery.approvals", "clientApprovals", "inbox", "delivery", { params: { view: "approvals" } }),
      node("delivery", "delivery.change-orders", "changeOrders", "docs", "delivery", { params: { view: "change-orders" } }),
      node("delivery", "delivery.risks", "risksAndIssues", "attention", "delivery", { params: { view: "risks" } }),
      node("delivery", "delivery.time", "timeEntries", "calendar", "delivery", { params: { view: "time" } }),
      node("delivery", "delivery.portal", "clientPortal", "clients", "delivery", { params: { view: "portal" } }),
      node("delivery", "delivery.templates", "deliveryTemplates", "templates", "delivery", { params: { view: "templates" } }),
      node("delivery", "delivery.reports", "deliveryReports", "reports", "reports", { params: { view: "delivery" } }),
    ],
  },
  {
    id: "resources", labelKey: "resources", iconId: "resources", routeId: "resources", required: true, opensPanel: true, readResources: ["team", "project"], accessMode: "any",
    nodes: [
      node("resources", "resources.overview", "resourceOverview", "overview", "resources", { required: true }),
      node("resources", "resources.people", "people", "members", "resources", { params: { view: "people" } }),
      node("resources", "resources.teams", "teams", "members", "resources", { params: { view: "teams" } }),
      node("resources", "resources.contractors", "contractors", "members", "resources", { params: { view: "contractors" } }),
      node("resources", "resources.skills", "skills", "tags", "resources", { params: { view: "skills" } }),
      node("resources", "resources.capacity", "capacity", "calendar", "resources", { params: { view: "capacity" } }),
      node("resources", "resources.allocations", "allocations", "projects", "resources", { params: { view: "allocations" } }),
      node("resources", "resources.workload", "workload", "tasks", "resources", { params: { view: "workload" } }),
      node("resources", "resources.availability", "availability", "calendar", "resources", { params: { view: "availability" } }),
      node("resources", "resources.leave", "leave", "calendar", "resources", { params: { view: "leave" } }),
      node("resources", "resources.hiring", "hiringDemand", "attention", "resources", { params: { view: "hiring" } }),
      node("resources", "resources.scenarios", "scenarios", "overview", "resources", { params: { view: "scenarios" } }),
      node("resources", "resources.rate-cards", "rateCards", "billing", "resources", { params: { view: "rate-cards" } }),
      node("resources", "resources.reports", "resourceReports", "reports", "resources", { params: { view: "reports" } }),
    ],
  },
  {
    id: "finance", labelKey: "finance", iconId: "finance", routeId: "finance", required: true, opensPanel: true, readResources: ["finance"],
    nodes: [
      node("finance", "finance.overview", "financeOverview", "overview", "finance", { required: true }),
      node("finance", "finance.project-budgets", "projectBudgets", "projects", "finance", { params: { view: "project-budgets" } }),
      node("finance", "finance.engagement-budgets", "engagementBudgets", "delivery", "finance", { params: { view: "engagement-budgets" } }),
      node("finance", "finance.estimates", "estimates", "docs", "finance", { params: { view: "estimates" } }),
      node("finance", "finance.rate-cards", "rateCards", "billing", "finance", { params: { view: "rate-cards" } }),
      node("finance", "finance.expenses", "expenses", "billing", "finance", { params: { view: "expenses" } }),
      node("finance", "finance.invoices", "invoices", "docs", "finance", { params: { view: "invoices" } }),
      node("finance", "finance.payments", "payments", "billing", "finance", { params: { view: "payments" } }),
      node("finance", "finance.retainers", "retainers", "billing", "finance", { params: { view: "retainers" } }),
      node("finance", "finance.receivable", "accountsReceivable", "attention", "finance", { params: { view: "receivable" } }),
      node("finance", "finance.payable", "accountsPayable", "attention", "finance", { params: { view: "payable" } }),
      node("finance", "finance.vendors", "vendors", "members", "finance", { params: { view: "vendors" } }),
      node("finance", "finance.banking", "banking", "billing", "finance", { params: { view: "banking" } }),
      node("finance", "finance.reconciliation", "reconciliation", "completed", "finance", { params: { view: "reconciliation" } }),
      node("finance", "finance.accounts", "chartOfAccounts", "tasks", "finance", { params: { view: "chart-of-accounts" } }),
      node("finance", "finance.journals", "journalEntries", "docs", "finance", { params: { view: "journal-entries" } }),
      node("finance", "finance.ledger", "generalLedger", "tasks", "finance", { params: { view: "ledger" } }),
      node("finance", "finance.tax", "tax", "billing", "finance", { params: { view: "tax" } }),
      node("finance", "finance.period-close", "periodClose", "calendar", "finance", { params: { view: "period-close" } }),
      node("finance", "finance.reports", "financialReports", "reports", "finance", { params: { view: "reports" } }),
    ],
  },
  {
    id: "reports", labelKey: "reports", iconId: "reports", routeId: "reports", required: true, opensPanel: true, readResources: ["report"],
    nodes: [
      node("reports", "reports.executive", "executive", "overview", "reports", { params: { view: "executive" }, required: true }),
      node("reports", "reports.sales", "sales", "deals", "reports", { params: { view: "sales" } }),
      node("reports", "reports.pipeline", "pipeline", "deals", "reports", { params: { view: "pipeline" } }),
      node("reports", "reports.delivery", "delivery", "delivery", "reports", { params: { view: "delivery" } }),
      node("reports", "reports.utilization", "resourceUtilization", "resources", "reports", { params: { view: "resource_utilization" } }),
      node("reports", "reports.capacity", "capacity", "calendar", "reports", { params: { view: "capacity" } }),
      node("reports", "reports.project-profitability", "projectProfitability", "finance", "reports", { params: { view: "project_profitability" } }),
      node("reports", "reports.client-profitability", "clientProfitability", "finance", "reports", { params: { view: "client_profitability" } }),
      node("reports", "reports.finance", "finance", "finance", "reports", { params: { view: "finance" } }),
      node("reports", "reports.tax", "tax", "billing", "reports", { params: { view: "tax" } }),
      node("reports", "reports.saved", "savedReports", "reports", "reports", { params: { view: "saved" } }),
      node("reports", "reports.scheduled", "scheduledReports", "calendar", "reports", { params: { view: "scheduled" } }),
      node("reports", "reports.builder", "reportBuilder", "automations", "reports", { params: { view: "builder" } }),
    ],
  },
  {
    id: "automations", labelKey: "automations", iconId: "automations", routeId: "automations", required: true, opensPanel: true, readResources: ["organization"],
    nodes: [
      node("automations", "automations.coming-soon", "comingSoon", "automations", "automations", { required: true }),
    ],
  },
  {
    id: "admin", labelKey: "admin", iconId: "admin", routeId: "organization", required: true, opensPanel: true, readResources: ["organization"], requiredAction: "update",
    nodes: [
      node("admin", "admin.organization", "organization", "admin", "organization", { required: true }),
      node("admin", "admin.members", "members", "members", "organization", { params: { tab: "members" } }),
      node("admin", "admin.teams-roles", "teamsAndRoles", "members", "team"),
      node("admin", "admin.spaces", "spaces", "spaces", "organizationSpaces"),
      node("admin", "admin.permissions", "permissions", "permissions", "permissions"),
      node("admin", "admin.workflows-statuses", "workflowsAndStatuses", "automations", "adminConfig", { params: { view: "workflows-statuses" } }),
      node("admin", "admin.custom-fields", "customFields", "tags", "adminConfig", { params: { view: "custom-fields" } }),
      node("admin", "admin.templates", "templates", "templates", "adminConfig", { params: { view: "templates" } }),
      node("admin", "admin.portal-branding", "clientPortalBranding", "delivery", "adminConfig", { params: { view: "portal-branding" } }),
      node("admin", "admin.notifications", "notifications", "inbox", "organization", { params: { tab: "notifications" } }),
      node("admin", "admin.integrations", "integrations", "integrations", "integrations"),
      node("admin", "admin.api-keys", "apiKeys", "permissions", "organization", { params: { tab: "apiKeys" } }),
      node("admin", "admin.mcp", "mcpConnections", "mcp", "mcp"),
      node("admin", "admin.billing", "billingEntitlements", "billing", "billing"),
      node("admin", "admin.security", "security", "permissions", "adminConfig", { params: { view: "security" } }),
      node("admin", "admin.audit", "auditLog", "recent", "organizationActivity"),
      node("admin", "admin.import-export", "dataImportExport", "docs", "adminConfig", { params: { view: "import-export" } }),
      node("admin", "admin.searchPolicy", "searchPolicy", "search", "searchPolicy"),
      node("admin", "admin.retention", "retention", "calendar", "adminConfig", { params: { view: "retention" } }),
      node("admin", "admin.features", "featureConfiguration", "admin", "adminConfig", { params: { view: "features" } }),
    ],
  },
] as const;
