/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "qentrah-bg": "#FAF8F4",
        "qentrah-surface": "#FFFFFF",
        "qentrah-surface-secondary": "#F5F2EC",
        "qentrah-surface-tertiary": "#EFEAE2",
        "qentrah-dark": "#090909",
        "qentrah-soft-dark": "#121212",
        "qentrah-text": "#111111",
        "qentrah-text-secondary": "#4D4D4D",
        "qentrah-text-muted": "#787878",
        "qentrah-border": "#DED8CF",
        "qentrah-border-strong": "#D5CEC4",
        "qentrah-primary": "#111111",
        "qentrah-primary-hover": "#222222",
        "qentrah-secondary": "#F5F2EC",
        "qentrah-muted": "#EFEAE2",
        "qentrah-card": "#FFFFFF",

        "qentrah-network-blue": "#4F80FF",
        "qentrah-agent-purple": "#8A5CFF",
        "qentrah-human-green": "#2BB673",
        "qentrah-automation-orange": "#FF9A3D",
        "qentrah-data-cyan": "#00A3FF",
        "qentrah-system-gray": "#5D6570",

        "qentrah-success": "#5F7768",
        "qentrah-warning": "#B78544",
        "qentrah-danger": "#A55B52",
        "qentrah-info": "#4388FF",
      },
      borderColor: {
        divider: "#DED8CF",
      },
      fontFamily: {
        sans: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold", "Inter_700Bold"],
        display: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold", "Inter_700Bold"],
        medium: ["Inter_500Medium"],
        semibold: ["Inter_600SemiBold"],
        bold: ["Inter_700Bold"],
      },
      borderRadius: {
        none: "0px",
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "10px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "20px",
        "4xl": "24px",
        pill: "999px",
      },
      boxShadow: {
        calm: "0px 2px 8px rgba(0,0,0,0.06)",
        elevated: "0px 8px 24px rgba(0,0,0,0.08)",
        floating: "0px 16px 48px rgba(0,0,0,0.12)",
      },
      spacing: {
        "0": "0px",
        "0.5": "2px",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "14": "56px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
        "32": "128px",
      },
    },
  },
  plugins: [],
};
