/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "qentrah-bg": "#FAF8F4",
        "qentrah-surface": "#FFFFFF",
        "qentrah-surface-secondary": "#F5F3EF",
        "qentrah-surface-tertiary": "#ECE8E1",
        "qentrah-dark": "#090909",
        "qentrah-soft-dark": "#121212",
        "qentrah-text": "#111111",
        "qentrah-text-secondary": "#5A5A5A",
        "qentrah-text-muted": "#8E8E8E",
        "qentrah-border": "#E5E2DD",
        "qentrah-border-strong": "#D2CEC8",
        "qentrah-primary": "#111111",
        "qentrah-primary-hover": "#222222",
        "qentrah-secondary": "#F5F3EF",
        "qentrah-muted": "#ECE8E1",
        "qentrah-card": "#FFFFFF",

        // Domain colors
        "qentrah-network-blue": "#4F80FF",
        "qentrah-agent-purple": "#8A5CFF",
        "qentrah-human-green": "#2BB673",
        "qentrah-automation-orange": "#FF9A3D",
        "qentrah-data-cyan": "#00A3FF",
        "qentrah-system-gray": "#5D6570",

        // Status
        "qentrah-success": "#19A65B",
        "qentrah-warning": "#FFB547",
        "qentrah-danger": "#FF5A5A",
        "qentrah-info": "#4388FF",
      },
      borderColor: {
        divider: "#E5E2DD",
      },
      fontFamily: {
        sans: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold", "Inter_700Bold"],
        display: ["Inter_400Regular", "Inter_500Medium", "Inter_600SemiBold", "Inter_700Bold"],
        medium: ["Inter_500Medium"],
        semibold: ["Inter_600SemiBold"],
        bold: ["Inter_700Bold"],
      },
      borderRadius: {
        none: "0px",
        xs: "6px",
        sm: "10px",
        md: "14px",
        lg: "18px",
        xl: "24px",
        "2xl": "32px",
        "3xl": "40px",
        pill: "9999px",
      },
      boxShadow: {
        calm: "0px 4px 12px rgba(0,0,0,0.04)",
        elevated: "0px 8px 24px rgba(0,0,0,0.08)",
        floating: "0px 16px 48px rgba(0,0,0,0.12)",
      },
      spacing: {
        "0": "0px",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "7": "28px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
      },
    },
  },
  plugins: [],
};
