import { defineTable } from "convex/server";
import { v } from "convex/values";
import { accountingPeriodStatusValidator, accountSystemKeyValidator, accountTypeValidator, bankTransactionStatusValidator, documentStatusValidator, estimateStatusValidator, journalStatusValidator, paymentStatusValidator, scopeTypeValidator, taxCalculationValidator } from "../finance/validators";

const audit = { createdByUserId: v.string(), createdAt: v.number(), updatedAt: v.number(), deletedAt: v.optional(v.number()) };
const dimensions = { clientId: v.optional(v.id("clients")), engagementId: v.optional(v.id("engagements")), projectId: v.optional(v.id("projects")), spaceId: v.optional(v.id("spaces")), serviceKey: v.optional(v.string()) };
const currencyAmounts = { currency: v.string(), amountMinor: v.number(), baseCurrency: v.string(), baseAmountMinor: v.number(), exchangeRateMicros: v.number() };

export const financeTables = {
  financeSettings: defineTable({ organizationId: v.string(), baseCurrency: v.string(), fiscalYearStartMonth: v.number(), invoicePrefix: v.string(), nextInvoiceNumber: v.number(), lockDate: v.optional(v.number()), ...audit }).index("by_org", ["organizationId"]),
  financeAccounts: defineTable({ organizationId: v.string(), code: v.string(), name: v.string(), type: accountTypeValidator, systemKey: v.optional(accountSystemKeyValidator), currency: v.optional(v.string()), active: v.boolean(), ...audit }).index("by_org_code", ["organizationId", "code"]).index("by_org_system", ["organizationId", "systemKey"]),
  financeAccountingPeriods: defineTable({ organizationId: v.string(), name: v.string(), startAt: v.number(), endAt: v.number(), status: accountingPeriodStatusValidator, closedByUserId: v.optional(v.string()), closedAt: v.optional(v.number()), ...audit }).index("by_org_status_start", ["organizationId", "status", "startAt"]).index("by_org_end", ["organizationId", "endAt"]),
  financeTaxRules: defineTable({ organizationId: v.string(), name: v.string(), jurisdiction: v.string(), rateBasisPoints: v.number(), calculation: taxCalculationValidator, exempt: v.boolean(), effectiveFrom: v.number(), effectiveTo: v.optional(v.number()), liabilityAccountId: v.id("financeAccounts"), active: v.boolean(), ...audit }).index("by_org_active_effective", ["organizationId", "active", "effectiveFrom"]),
  financeBudgets: defineTable({ organizationId: v.string(), name: v.string(), scopeType: scopeTypeValidator, scopeId: v.string(), periodStartAt: v.number(), periodEndAt: v.number(), category: v.string(), currency: v.string(), amountMinor: v.number(), baseAmountMinor: v.number(), exchangeRateMicros: v.number(), status: v.union(v.literal("draft"), v.literal("approved"), v.literal("archived")), ...audit }).index("by_scope_period", ["organizationId", "scopeType", "scopeId", "periodStartAt"]).index("by_org_status_period", ["organizationId", "status", "periodStartAt"]),
  financeEstimates: defineTable({ organizationId: v.string(), number: v.string(), title: v.string(), status: estimateStatusValidator, clientId: v.id("clients"), engagementId: v.optional(v.id("engagements")), projectId: v.optional(v.id("projects")), currency: v.string(), subtotalMinor: v.number(), taxMinor: v.number(), totalMinor: v.number(), baseTotalMinor: v.number(), exchangeRateMicros: v.number(), validUntil: v.optional(v.number()), acceptedAt: v.optional(v.number()), ...audit }).index("by_org_status_updated", ["organizationId", "status", "updatedAt"]).index("by_client", ["organizationId", "clientId", "updatedAt"]),
  financeEstimateLines: defineTable({ organizationId: v.string(), estimateId: v.id("financeEstimates"), description: v.string(), quantity: v.number(), unitAmountMinor: v.number(), netMinor: v.number(), taxMinor: v.number(), totalMinor: v.number(), taxRuleId: v.optional(v.id("financeTaxRules")), order: v.number(), ...dimensions, ...audit }).index("by_estimate_order", ["organizationId", "estimateId", "order"]),
  financeInvoices: defineTable({ organizationId: v.string(), number: v.string(), status: documentStatusValidator, clientId: v.id("clients"), engagementId: v.optional(v.id("engagements")), projectId: v.optional(v.id("projects")), estimateId: v.optional(v.id("financeEstimates")), issueAt: v.number(), dueAt: v.number(), currency: v.string(), subtotalMinor: v.number(), taxMinor: v.number(), totalMinor: v.number(), baseTotalMinor: v.number(), paidMinor: v.number(), exchangeRateMicros: v.number(), journalEntryId: v.optional(v.id("financeJournalEntries")), postedAt: v.optional(v.number()), ...audit }).index("by_org_status_due", ["organizationId", "status", "dueAt"]).index("by_client_updated", ["organizationId", "clientId", "updatedAt"]).index("by_project", ["organizationId", "projectId", "updatedAt"]).index("by_engagement", ["organizationId", "engagementId", "updatedAt"]),
  financeInvoiceLines: defineTable({ organizationId: v.string(), invoiceId: v.id("financeInvoices"), description: v.string(), quantity: v.number(), unitAmountMinor: v.number(), netMinor: v.number(), taxMinor: v.number(), totalMinor: v.number(), taxRuleId: v.optional(v.id("financeTaxRules")), timeEntryId: v.optional(v.id("deliveryTimeEntries")), order: v.number(), ...dimensions, ...audit }).index("by_invoice_order", ["organizationId", "invoiceId", "order"]),
  financeVendors: defineTable({ organizationId: v.string(), name: v.string(), taxIdentifier: v.optional(v.string()), currency: v.string(), active: v.boolean(), ...audit }).index("by_org_active_name", ["organizationId", "active", "name"]),
  financeExpenses: defineTable({ organizationId: v.string(), vendorId: v.optional(v.id("financeVendors")), description: v.string(), status: documentStatusValidator, incurredAt: v.number(), dueAt: v.optional(v.number()), expenseAccountId: v.id("financeAccounts"), taxRuleId: v.optional(v.id("financeTaxRules")), ...currencyAmounts, taxMinor: v.number(), baseTaxMinor: v.number(), journalEntryId: v.optional(v.id("financeJournalEntries")), paymentId: v.optional(v.id("financePayments")), ...dimensions, ...audit }).index("by_org_status_incurred", ["organizationId", "status", "incurredAt"]).index("by_project", ["organizationId", "projectId", "incurredAt"]).index("by_vendor", ["organizationId", "vendorId", "incurredAt"]),
  financePayments: defineTable({ organizationId: v.string(), direction: v.union(v.literal("inbound"), v.literal("outbound")), status: paymentStatusValidator, receivedOrPaidAt: v.number(), method: v.string(), reference: v.optional(v.string()), clientId: v.optional(v.id("clients")), vendorId: v.optional(v.id("financeVendors")), bankAccountId: v.optional(v.id("financeBankAccounts")), ...currencyAmounts, journalEntryId: v.id("financeJournalEntries"), ...audit }).index("by_org_direction_date", ["organizationId", "direction", "receivedOrPaidAt"]).index("by_client", ["organizationId", "clientId", "receivedOrPaidAt"]).index("by_vendor", ["organizationId", "vendorId", "receivedOrPaidAt"]),
  financePaymentApplications: defineTable({ organizationId: v.string(), paymentId: v.id("financePayments"), invoiceId: v.optional(v.id("financeInvoices")), expenseId: v.optional(v.id("financeExpenses")), retainerId: v.optional(v.id("financeRetainers")), amountMinor: v.number(), baseAmountMinor: v.number(), createdByUserId: v.string(), createdAt: v.number() }).index("by_payment", ["organizationId", "paymentId"]).index("by_invoice", ["organizationId", "invoiceId"]).index("by_expense", ["organizationId", "expenseId"]),
  financeRetainers: defineTable({ organizationId: v.string(), engagementId: v.id("engagements"), clientId: v.id("clients"), paymentId: v.id("financePayments"), currency: v.string(), receivedMinor: v.number(), appliedMinor: v.number(), baseReceivedMinor: v.number(), exchangeRateMicros: v.number(), status: v.union(v.literal("active"), v.literal("exhausted"), v.literal("refunded")), ...audit }).index("by_engagement_status", ["organizationId", "engagementId", "status"]).index("by_client", ["organizationId", "clientId", "updatedAt"]),
  financeJournalEntries: defineTable({ organizationId: v.string(), number: v.string(), accountingDate: v.number(), description: v.string(), status: journalStatusValidator, sourceType: v.string(), sourceId: v.string(), reversalOfId: v.optional(v.id("financeJournalEntries")), reversedById: v.optional(v.id("financeJournalEntries")), postedByUserId: v.string(), postedAt: v.number(), ...audit }).index("by_org_date", ["organizationId", "accountingDate"]).index("by_source", ["organizationId", "sourceType", "sourceId"]).index("by_reversal", ["organizationId", "reversalOfId"]),
  financeLedgerLines: defineTable({ organizationId: v.string(), journalEntryId: v.id("financeJournalEntries"), accountId: v.id("financeAccounts"), accountingDate: v.number(), currency: v.string(), debitMinor: v.number(), creditMinor: v.number(), baseCurrency: v.string(), debitBaseMinor: v.number(), creditBaseMinor: v.number(), description: v.optional(v.string()), ...dimensions, createdAt: v.number() }).index("by_period_account", ["organizationId", "accountingDate", "accountId"]).index("by_journal", ["organizationId", "journalEntryId"]).index("by_project_date", ["organizationId", "projectId", "accountingDate"]).index("by_engagement_date", ["organizationId", "engagementId", "accountingDate"]).index("by_client_date", ["organizationId", "clientId", "accountingDate"]).index("by_space_date", ["organizationId", "spaceId", "accountingDate"]),
  financeBankAccounts: defineTable({ organizationId: v.string(), name: v.string(), currency: v.string(), ledgerAccountId: v.id("financeAccounts"), active: v.boolean(), ...audit }).index("by_org_active", ["organizationId", "active"]),
  financeBankTransactions: defineTable({ organizationId: v.string(), bankAccountId: v.id("financeBankAccounts"), externalId: v.string(), occurredAt: v.number(), description: v.string(), amountMinor: v.number(), currency: v.string(), status: bankTransactionStatusValidator, paymentId: v.optional(v.id("financePayments")), reconciledByUserId: v.optional(v.string()), reconciledAt: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() }).index("by_account_date", ["organizationId", "bankAccountId", "occurredAt"]).index("by_external", ["organizationId", "bankAccountId", "externalId"]).index("by_org_status_date", ["organizationId", "status", "occurredAt"]),
};
