import { v } from "convex/values";
import {
  savedViewConfigValidator,
  scopeTypeValidator,
  viewTypeValidator,
  workOsRecordResourceValidator,
} from "../schema/validators";

export const seedWorkspaceDefaultsResultValidator = v.object({
  workflowDefinitionsCreated: v.number(),
  workflowStatesCreated: v.number(),
  surfacesCreated: v.number(),
  savedViewsCreated: v.number(),
  surfaceTabsCreated: v.number(),
});

export const surfaceValidator = v.object({
  _id: v.id("surfaces"),
  _creationTime: v.number(),
  organizationId: v.string(),
  scopeType: scopeTypeValidator,
  scopeId: v.optional(v.string()),
  key: v.string(),
  title: v.string(),
  ownerUserId: v.optional(v.string()),
  visibility: v.union(v.literal("private"), v.literal("space_members"), v.literal("organization")),
  recordState: v.union(v.literal("active"), v.literal("archived"), v.literal("deleted")),
  createdByUserId: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  deletedAt: v.optional(v.number()),
});

export const surfaceTabValidator = v.object({
  _id: v.id("surfaceTabs"),
  _creationTime: v.number(),
  organizationId: v.string(),
  surfaceId: v.id("surfaces"),
  tabType: v.union(v.literal("savedView"), v.literal("record"), v.literal("system")),
  label: v.string(),
  icon: v.optional(v.string()),
  order: v.number(),
  savedViewId: v.optional(v.id("savedViews")),
  recordType: v.optional(workOsRecordResourceValidator),
  recordId: v.optional(v.string()),
  systemKey: v.optional(v.string()),
  ownerUserId: v.optional(v.string()),
  visibility: v.union(v.literal("private"), v.literal("space_members"), v.literal("organization")),
  recordState: v.union(v.literal("active"), v.literal("archived"), v.literal("deleted")),
  createdByUserId: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  deletedAt: v.optional(v.number()),
});

export const savedViewValidator = v.object({
  _id: v.id("savedViews"),
  _creationTime: v.number(),
  organizationId: v.string(),
  resourceType: workOsRecordResourceValidator,
  viewType: viewTypeValidator,
  name: v.string(),
  description: v.optional(v.string()),
  ownerUserId: v.optional(v.string()),
  scopeType: scopeTypeValidator,
  scopeId: v.optional(v.string()),
  visibility: v.union(v.literal("private"), v.literal("space_members"), v.literal("organization")),
  config: savedViewConfigValidator,
  isDefault: v.optional(v.boolean()),
  sourceTemplateId: v.optional(v.string()),
  isSystemDefault: v.optional(v.boolean()),
  isRemovable: v.boolean(),
  recordState: v.union(v.literal("active"), v.literal("archived"), v.literal("deleted")),
  createdByUserId: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  deletedAt: v.optional(v.number()),
});

export const workflowStateValidator = v.object({
  _id: v.id("workflowStates"),
  _creationTime: v.number(),
  organizationId: v.string(),
  workflowId: v.id("workflowDefinitions"),
  key: v.string(),
  label: v.string(),
  color: v.string(),
  order: v.number(),
  category: v.union(
    v.literal("not_started"),
    v.literal("active"),
    v.literal("waiting"),
    v.literal("terminal"),
  ),
  isDefault: v.boolean(),
  isTerminal: v.boolean(),
  isRemovable: v.boolean(),
  sourceTemplateId: v.optional(v.string()),
  recordState: v.union(v.literal("active"), v.literal("archived"), v.literal("deleted")),
  createdByUserId: v.string(),
  createdAt: v.number(),
  updatedAt: v.number(),
  deletedAt: v.optional(v.number()),
});
